insert  into  TbCargo VALUES(	'	Administrador 	'	,	'	Nivel:1	'	,	8000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Contador 	'	,	'	Nivel:2	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Tecnico Sistemas	'	,	'	Nivel:3	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Tecnico Enfermeria	'	,	'	Nivel:4	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Tecnico Rayos X	'	,	'	Nivel:4	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Tecnico Imagenologia	'	,	'	Nivel:5	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Tecnico Laboratorio	'	,	'	Nivel:6	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Auxliar 	'	,	'	Nivel:7	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Encargado	'	,	'	Nivel:8	'	,	6000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Camillero	'	,	'	Nivel:9	'	,	6000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Tecnicos	'	,	'	Nivel:10	'	,	5000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Jefe Servicios Grales	'	,	'	Nivel:11	'	,	7000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Guardia	'	,	'	Nivel:12	'	,	5000	,	'	AC	'	)
insert  into  TbCargo VALUES(	'	Cajero	'	,	'	Nivel:12	'	,	5000	,	'	AC	'	)