insert into tbServicio VALUES(	'	HOSPITALIZACION	'	,	160	,	'	AC	'	)
insert into tbServicio VALUES(	'	CONSULTA EXTERNA	'	,	20	,	'	AC	'	)
insert into tbServicio VALUES(	'	ANATOMIA PATOLOGICA	'	,	402	,	'	AC	'	)
insert into tbServicio VALUES(	'	ANESTESIOLOGIA Y REANIMACION	'	,	57	,	'	AC	'	)
insert into tbServicio VALUES(	'	BANCO DE SANGRE	'	,	224	,	'	AC	'	)
insert into tbServicio VALUES(	'	BETATERAPIA	'	,	191	,	'	AC	'	)
insert into tbServicio VALUES(	'	BRONCOSCOPIA	'	,	248	,	'	AC	'	)
insert into tbServicio VALUES(	'	CAMPAÑA MAMOGRAFICA	'	,	247	,	'	AC	'	)
insert into tbServicio VALUES(	'	CISTOSCOPIA	'	,	295	,	'	AC	'	)
insert into tbServicio VALUES(	'	COBALTOTERAPIA	'	,	395	,	'	AC	'	)
insert into tbServicio VALUES(	'	COLPOSCOPIA	'	,	260	,	'	AC	'	)
insert into tbServicio VALUES(	'	DEPOSITOS EN GARANTIA	'	,	467	,	'	AC	'	)
insert into tbServicio VALUES(	'	ECOCARDIOGRAFIA	'	,	284	,	'	AC	'	)
insert into tbServicio VALUES(	'	ECOGRAFIA	'	,	162	,	'	AC	'	)
insert into tbServicio VALUES(	'	ELECTROCARDIOGRAFIA	'	,	185	,	'	AC	'	)
insert into tbServicio VALUES(	'	ELECTROENCEFALOGRAMA	'	,	362	,	'	AC	'	)
insert into tbServicio VALUES(	'	ELECTROMIOGRAFIA	'	,	214	,	'	AC	'	)
insert into tbServicio VALUES(	'	EMERGENCIA	'	,	340	,	'	AC	'	)
insert into tbServicio VALUES(	'	EMERGENCIA CIRUGIA GENERAL	'	,	350	,	'	AC	'	)
insert into tbServicio VALUES(	'	EMERGENCIA GINECO-OBSTETRICA	'	,	81	,	'	AC	'	)
insert into tbServicio VALUES(	'	EMERGENCIA MEDICINA GENERAL	'	,	221	,	'	AC	'	)
insert into tbServicio VALUES(	'	EMERGENCIA PEDIATRICA	'	,	189	,	'	AC	'	)
insert into tbServicio VALUES(	'	ENDOSCOPIA DIGESTIVA	'	,	160	,	'	AC	'	)
insert into tbServicio VALUES(	'	ENFERMERIA	'	,	499	,	'	AC	'	)
insert into tbServicio VALUES(	'	ERGOMETRIA	'	,	388	,	'	AC	'	)
insert into tbServicio VALUES(	'	FISIOTERAPIA	'	,	70	,	'	AC	'	)
insert into tbServicio VALUES(	'	FONOCARDIOGRAFIA	'	,	150	,	'	AC	'	)
insert into tbServicio VALUES(	'	HEMATOLOGIA	'	,	116	,	'	AC	'	)
insert into tbServicio VALUES(	'	HEMODIALISIS - DIALISIS	'	,	59	,	'	AC	'	)
insert into tbServicio VALUES(	'	HOOLTER	'	,	135	,	'	AC	'	)
insert into tbServicio VALUES(	'	LABORATORIO	'	,	18	,	'	AC	'	)
insert into tbServicio VALUES(	'	MAMOGRAFIA	'	,	258	,	'	AC	'	)
insert into tbServicio VALUES(	'	MORGE	'	,	433	,	'	AC	'	)
insert into tbServicio VALUES(	'	PROMOCION EN SALUD	'	,	446	,	'	AC	'	)
insert into tbServicio VALUES(	'	PRUEBA 	'	,	35	,	'	AC	'	)
insert into tbServicio VALUES(	'	QUIMIOTERAPIA	'	,	213	,	'	AC	'	)
insert into tbServicio VALUES(	'	QUIROFANO	'	,	56	,	'	AC	'	)
insert into tbServicio VALUES(	'	RADIOTERAPIA	'	,	45	,	'	AC	'	)
insert into tbServicio VALUES(	'	RAYOS X	'	,	216	,	'	AC	'	)
insert into tbServicio VALUES(	'	RESONANCIA MAGNETICA	'	,	60	,	'	AC	'	)
insert into tbServicio VALUES(	'	SALUD OCUPACIONAL	'	,	159	,	'	AC	'	)
insert into tbServicio VALUES(	'	SALUD REPRODUCTIVA	'	,	499	,	'	AC	'	)
insert into tbServicio VALUES(	'	SERVICIOS DE LABORATORIO	'	,	352	,	'	AC	'	)
insert into tbServicio VALUES(	'	SPS IMAGENOLOGIA	'	,	203	,	'	AC	'	)
insert into tbServicio VALUES(	'	SPS LABORATORIO	'	,	87	,	'	AC	'	)
insert into tbServicio VALUES(	'	SPS TRASLADOS	'	,	423	,	'	AC	'	)
insert into tbServicio VALUES(	'	TOMOGRAFIA AXIAL COMPUTARIZADA	'	,	258	,	'	AC	'	)
insert into tbServicio VALUES(	'	TRABAJO SOCIAL	'	,	107	,	'	AC	'	)
insert into tbServicio VALUES(	'	UNIDAD DE CUIDADOS INTERMEDIOS (UCI)	'	,	273	,	'	AC	'	)
insert into tbServicio VALUES(	'	UNIDAD DE TERAPIA INTENSIVA (UTI)	'	,	157	,	'	AC	'	)
insert into tbServicio VALUES(	'	UNIDAD TRANSFUSIONAL	'	,	147	,	'	AC	'	)
insert into tbServicio VALUES(	'	VACUNAS	'	,	160	,	'	AC	'	)
