CREATE TABLE [dbo].[TbCama](
	[Id_Cama] [int] IDENTITY(1,1) NOT NULL,
	[Id_Sala_Cam] [int] NULL,
	[Numero_Cam] [nvarchar](20) NULL,
	[Estado_Cam] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Cama] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]