CREATE TABLE [dbo].[TbCIE](
	[Id_CIE] [int] IDENTITY(1,1) NOT NULL,
	[Sigla_CIE] [nvarchar](50) NULL,
	[Nombre_CIE] [nvarchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_CIE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]