CREATE TABLE [dbo].[TbMedico](
	[Id_Medico] [int] IDENTITY(1,1) NOT NULL,
	[Id_Persona_Med] [int] NULL,
	[Id_Especialidad_Med] [int] NULL,
	[estado_med] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Medico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
