CREATE TABLE [dbo].[TbOcupacion](
	[Id_Ocupacion] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion_Ocu] [varchar](50) NULL,
	[Estado_Ocu] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Ocupacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
